# Generated by "terraform_state_backend" module, below
terraform {
  backend "s3" {
    region         = "us-east-1"
    bucket         = "halcyon-city-prod-terraform-state"
    key            = "terraform.tfstate"
    dynamodb_table = "halcyon-city-prod-terraform-state-lock"
    encrypt        = true
  }
}